apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adt-utilityservice.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-utilityservice.labels" . | nindent 4 }}
data:
    spring.zipkin.baseUrl: "http://zipkin:9411/"
    spring.mail.host: "smtp.gmail.com"
    spring.mail.username: "alphadotsit.adt@gmail.com"
    spring.mail.password: "tplyqqiwdwsvtdux"
    spring.mail.properties.mail.smtp.auth: "true"