apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "adt-hrms.fullname" . }}-configmap
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "adt-hrms.labels" . | nindent 4 }}
data:
    spring.zipkin.baseUrl: "http://zipkin:9411/"
    spring.jpa.hibernate.ddl-auto: none
    spring.datasource.hikari.connection-timeout: "20000"
    spring.datasource.hikari.minimum-idle: "2"
    spring.datasource.hikari.maximum-pool-size: "2"
    spring.datasource.hikari.idle-timeout: "300000"
    spring.datasource.hikari.max-lifetime: "1800000"
    spring.datasource.hikari.auto-commit: "true"
    spring.datasource.hikari.validation-query: "SELECT 1"
    spring.datasource.hikari.connectionTimeoutRetry: "3"
    spring.profile.active: "sit"

