apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "adt-hrms.fullname" . }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "adt-hrms.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "adt-hrms.labels" . | nindent 8 }}
    spec:
      containers:
      - env:
        - name: server.port
          value: "{{ .Values.service.port }}"
        - name: "server.servlet.context-path"
          value: "/hrms"
        - name: spring.datasource.password
          valueFrom:
            secretKeyRef:
              name: sithrmspostgresqlpwd
              key: SIT-HRMS-POSTGRESQL-PWD
        - name: spring.datasource.username
          valueFrom:
            secretKeyRef:
              name: sithrmspostgresqlusername
              key: SIT-HRMS-POSTGRESQL-USERNAME
        - name: spring.datasource.url
          valueFrom:
            secretKeyRef:
              name: sithrmsdatabaseurl
              key: SIT-HRMS-DATABASE-URL          
        envFrom:
         - configMapRef: 
             name: {{ include "adt-hrms.fullname" . }}-configmap       
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: hrms
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
          protocol: TCP